import { ubj, buap, consultalia, warwick, microsoft } from "../assets/images";
import {
    docker,
    jira,
    vscode,
    java,
    python,
    c,
    flutter,
    tensorflow,
    pytorch,
    mysql,
    contact,
    css,
    express,
    git,
    github,
    html,
    javascript,
    linkedin,
    mongodb,
    nodejs,
    react,
    tailwindcss,
    typescript,
    sentiment,
    detection,
    celullar,
    game,
    
} from "../assets/icons";

/**
 * Constants representing various entities like skills, educations, experiences, social links, and projects.
 * These are structured as arrays of objects, each containing relevant information and used throughout the application.
 */
export const skills = [
    {
        imageUrl: python,
        name: "Python",
        type: "Development",
    },
    {
        imageUrl: tensorflow,
        name: "tensorflow",
        type: "Machine Learning",
    },
    {
        imageUrl: pytorch,
        name: "pytorch",
        type: "Machine Learning",
    },
    {
        imageUrl: java,
        name: "Java",
        type: "Development",
    },
    {
        imageUrl: c,
        name: "C",
        type: "Development",
    },
    {
        imageUrl: docker,
        name: "Docker",
        type: "Container",
    },
    {
        imageUrl: jira,
        name: "Jira",
        type: "Project Management",
    },
    {
        imageUrl: vscode,
        name: "VScode",
        type: "IDE",
    },
    {
        imageUrl: git,
        name: "Git",
        type: "Version Control",
    },
    {
        imageUrl: github,
        name: "GitHub",
        type: "Version Control",
    },
    {
        imageUrl: mysql,
        name: "MySQL",
        type: "Database",
    },
    {
        imageUrl: mongodb,
        name: "MongoDB",
        type: "Database",
    },
    {
        imageUrl: javascript,
        name: "JavaScript",
        type: "Frontend",
    },
    {
        imageUrl: typescript,
        name: "TypeScript",
        type: "Frontend",
    },
    {
        imageUrl: nodejs,
        name: "Node.js",
        type: "Backend",
    },
    {
        imageUrl: flutter,
        name: "Flutter",
        type: "Frontend",
    },
    {
        imageUrl: react,
        name: "React",
        type: "Frontend",
    },
    {
        imageUrl: html,
        name: "HTML",
        type: "Frontend",
    },
    {
        imageUrl: css,
        name: "CSS",
        type: "Frontend",
    },
    {
        imageUrl: tailwindcss,
        name: "Tailwind CSS",
        type: "Frontend",
    },
    {
        imageUrl: express,
        name: "Express",
        type: "Backend",
    },
];

export const educations = [
    {
        title: "Postgraduate (MSc. Computer Science)",
        company_name: "University of Warwick",
        icon: warwick,
        iconBg: "#E6E6FA",
        date: "September 2022 - January 2024",
        points: [
            "Driven by my interest in evolving technologies, I decided to further my studies in Machine Learning and AI, continuously enhancing my software development skills.",
            "In my research, 'Detection of Images Generated by AI Implementing Attention-Based Techniques,' I introduced a novel method to detect AI-generated images using Machine Learning.",
            "I discovered archery as a new hobby and sport, securing first place in the British Universities and Colleges Sports competition.",
            "Under the guidance of outstanding professors, I successfully earned my academic degree with Merit.",
        ],
    },
    {
        title: "Undergraduate (Engineering in Computer Science)",
        company_name: "Benemerita Universidad Autonoma de Puebla",
        icon: buap,
        iconBg: "#ADD8E6",
        date: "September 2016 - Jun 2021",
        points: [
             "Studied Computer Science and Computer Engineering under expert professors and colleges.",
             "Presented a paper titled 'Quality of Service as an Object Learning on Vehicular Networks' at a university conference.",
             "Founded a problem-solving club focused on algorithm design, complexity analysis, and data structures.",
             "In 2021, I participated in an exchange program at Lancaster University, UK, where I met exceptional professors.",
             "Awarded the Young Researchers Scholarship in 2020 for my project on the implementation of an IPV6 wireless network for smart cities."
        ],
    },
    {
        title: 'Certification: Career Essentials in Generative AI',
        company_name: "Microsoft",
        icon: microsoft,
        iconBg: "#FFFFFF",
        date: "December 2023",
        points: [
        ],
    },
    {
        title: "Certification: Career Essentials in Software Development",
        company_name: "Microsoft",
        icon: microsoft,
        iconBg: "#FFFFFF",
        date: "December 2023",
        points: [
        ],
    },
];

export const experiences = [
    {
        title: "Full stack Developer",
        company_name: "Consultalia",
        icon: consultalia,
        iconBg: "#F4F2F0",
        date: "June 2020 - June 2021",
        points: [ 
            "Developed a key module for online document signing, enabling encryption and decryption using user signatures. This module functions on both server and client sides, managing private and public keys effectively.",
            "Implemented secure storage of encrypted documents in a relational database, utilizing SHA256 and SHA512 algorithms for data security.",
            "Efficiently managed SQL queries for interactive communication between users and the server.",
            "Developing a cross-platform application (Web, Mobile, and Desktop) using Flutter, NodeJS, and TypeScript.",
            "Participating  in code reviews, providing constructive feedback to fellow developers to enhance software quality.",
        ],
    },
    {
        title: "Temporary Teacher",
        company_name: "High School UBJ",
        icon: ubj,
        iconBg: "#F2F2F2",
        date: "April 2022 - Aug 2022",
        points: [
            "Delivered lectures on Artificial Intelligence and Mechatronics, providing in-depth knowledge and practical insights.",
            "Mentored students in the design and construction of an articulated robot arm using recyclable materials, Arduino technology, and 3D printing techniques.",
            "Participated in interdisciplinary collaborations with faculty across various disciplines to design and implement comprehensive, student-centric projects aimed at improving multidimensional learning outcomes.",
            "Conducted extracurricular workshops on programming theory for more than 50 students.",
            "Provided career guidance and support to more than 100 students, assisting them in making informed career decisions.",
        ],
    },
];

export const socialLinks = [
    {
        name: 'Contact',
        iconUrl: contact,
        link: '/contact',
    },
    {
        name: 'GitHub',
        iconUrl: github,
        link: 'https://github.com/SCalcaneo',
    },
    {
        name: 'LinkedIn',
        iconUrl: linkedin,
        link: 'https://www.linkedin.com/in/sergiomaldonadocalcaneo',
    }
];

export const projects = [
    {
        iconUrl: detection,
        theme: 'btn-back-blue',
        name: 'Detection of AI-Generated Images',
        description: 'Research about attention implemented on a CNN Model that can identify images generated by AI adding attention-based techniques.',
        link: 'https://www.academia.edu/108091171',
    },
    {
        iconUrl: game,
        theme: 'btn-back-pink',
        name: 'Stategy storytelling videogame',
        description: 'Built a strategy videogame that tells a story depending on your decisions to be a software developer.',
        link: 'https://github.com/SCalcaneo',
    },
    {
        iconUrl: sentiment,
        theme: 'btn-back-black',
        name: 'Sentiment Classification for Social Media',
        description: 'A Large Short-Term Memory Model that can classify negative and positive tweets.',
        link: 'https://github.com/Scalcaneo/TweetMoodAnalyzer',
    },
    {
        iconUrl: celullar,
        theme: 'btn-back-green',
        name: 'Prediction of Cellular Composition',
        description: 'Develop a machine learning model for predicting the number of six different types of cells in a given histological image patch.',
        link: 'https://github.com/Scalcaneo/Development-Optimizatin-of-ResNet-18-Based-CNN-for-Automated-Cell-Counting-in-Histopathology-Images',
    },
];